name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "windows-latest", "macos-latest"]
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: configure
      run: cmake -Bbuild
    - name: Make
      run: cmake --build build
    - name: Test
      run: |
        build/main_ok
        build/main_broken
